# Include the Framework Team-owned directories.
include = [
    "framework/**/*.py",
    "api/**/*.py",
    "wodles/**/*.py",
    "integrations/**/*.py",
]

# Same as Black.
line-length = 120
indent-width = 4

# Assume Python 3.7
target-version = "py37"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F", "I001", "C901"]
ignore = ["F405"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[per-file-ignores]
"wodles/**/*.py" = ["E402"]
"api/test/integration/env/configurations/**/*.py" = ["E402"]
"__init__.py" = ["F401"]

[format]
# Like Black, use double quotes for strings.
quote-style = "single"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"