language: c

notifications:
  irc:
    - "chat.freenode.net#ossec-dev"

env:
- DB=mysql OSSEC_TYPE=server GEOIP=yes
- DB=mysql OSSEC_TYPE=server GEOIP=no
- DB=pgsql OSSEC_TYPE=server GEOIP=yes
- DB=pgsql OSSEC_TYPE=server GEOIP=no
- DB=none OSSEC_TYPE=server GEOIP=yes
- DB=none OSSEC_TYPE=server GEOIP=no
- DB=none OSSEC_TYPE=server GEOIP=no ALL=yes
- DB=none OSSEC_TYPE=agent GEOIP=no
- DB=none OSSEC_TYPE=winagent GEOIP=no
- OSSEC_TYPE=test


compiler:
- gcc
- clang


matrix:
  fast_finish: true
  exclude:
    - compiler: clang
      env: DB=none OSSEC_TYPE=winagent GEOIP=no



before_script:
- sudo apt-get update -qq
- if [[ "$GEOIP" == "yes"  ]]; then ( sudo apt-get install geoip-bin geoip-database libgeoip-dev libgeoip1 ); fi
- if [[ "$OSSEC_TYPE" == "winagent" ]]; then ( sudo apt-get install aptitude && sudo aptitude -y install mingw-w64 nsis ); fi
- if [[ "$OSSEC_TYPE" == "test" ]]; then ( sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ saucy main " && sudo apt-get update && sudo apt-get install check valgrind ); fi



script:
- COMMAND="V=1 TARGET=${OSSEC_TYPE}"
  && if ! [[ "${DB}" = "none" ]]; then COMMAND="${COMMAND} DATABASE=${DB}"; fi
  && if [[ "${GEOIP}" = "yes" ]]; then COMMAND="${COMMAND} USE_GEOIP=1"; fi
  && if [[ "${ALL}" = "yes" ]]; then COMMAND="${COMMAND} USE_ZEROMQ=1 USE_PRELUDE=1 USE_GEOIP=1"; fi
  && ( cd src/ && make ${COMMAND} settings && make ${COMMAND} -j )

- if [[ "$OSSEC_TYPE" == "test" ]]; then ( cd src/tests/ && make run_valgrind ); fi

before_deploy:
- mkdir travis-builds
- if [[ "$OSSEC_TYPE" == "winagent" ]]; then ( cp src/win-pkg/ossec-agent.exe travis-builds/ossec-agent-bid:$TRAVIS_JOB_NUMBER-br:$TRAVIS_BRANCH.exe ); fi


