name: "Compile"
description: "Executes a compilation."

inputs:
  path:
    required: true
    description: "Path to compile and test"
    default: src/

runs:
  using: "composite"
  steps:
      - name: Generate CMake project
        run: |
          SRC_FOLDER=$(pwd)/${{ inputs.path }}

          mkdir -p build && cd build
          cmake ${SRC_FOLDER} -DBUILD_TESTS=1 -G "Unix Makefiles"
          echo "CMake project generated in $(pwd)"
        shell: bash

      - name: Compile
        run: |
          cd build
          if [ ! -f CMakeCache.txt ]; then
            echo "CMake cache not found in $(pwd). Aborting."
            exit 1
          fi
          cmake --build .
        shell: bash

      - name: Run Tests
        continue-on-error: true
        run: |
          set +e
          cd build
          ctest || echo "Tests failed, but continuing"
        shell: bash
