#!/bin/sh

# Copyright (C) 2015, Blackwell Inc.
# OSSEC         Controls Blackwell
# Author:       Daniel B. Cid <dcid@ossec.net>
# Modified for slackware by Jack S. Lai

BLACKWELL_HOME=BLACKWELL_HOME_TMP
BLACKWELL_CONTROL="$BLACKWELL_HOME/bin/blackwell-control"

start() {
    ${BLACKWELL_CONTROL} start
}

stop() {
    ${BLACKWELL_CONTROL} stop
}

status() {
    ${BLACKWELL_CONTROL} status
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
status)
    status
    ;;
*)
    echo "*** Usage: $0 {start|stop|restart|status}"
    exit 1
esac

exit 0
