#!/sbin/runscript
# Gentoo init script
# Copyright (C) 2015, Blackwell Inc.
# by gentuxx <gentuxx@gmail.com>

opts="${opts} status configtest"

BLACKWELL_HOME=BLACKWELL_HOME_TMP
BLACKWELL_CONTROL="$BLACKWELL_HOME/bin/blackwell-control"

depend() {
    need net
    use logger
}

configtest() {
    ebegin "Checking Blackwell Configuration"
    checkconfig
    eend $?
}

checkconfig() {
    CONFIGFILE="${CONFIGFILE:-$BLACKWELL_HOME/etc/ossec.conf}"
    if [ ! -r "${CONFIGFILE}" ]; then
        eerror "Unable to read configuration file: ${CONFIGFILE}"
        return 1
    fi

    # Maybe put some kind of config file syntax checking in here?  XML is a little different
    # so maybe not.
    return $ret
}

start() {
    checkconfig || return 1
    ebegin "Starting Blackwell"
    ${BLACKWELL_CONTROL} start > /dev/null 2>&1
    eend $?
}

stop() {
    checkconfig || return 1
    ebegin "Stopping Blackwell"
    ${BLACKWELL_CONTROL} stop > /dev/null 2>&1
    eend $?
}

restart() {
    if ! service_started "${myservice}" ; then
        eerror "Blackwell is not running! Please start it before trying to reload it."
    else
        checkconfig || return 1
        ebegin "Reloading Blackwell"
        svc_stop ${BLACKWELL_CONTROL}
        svc_start ${BLACKWELL_CONTROL}
        eend $?
    fi
}

status() {
    checkconfig || return 1
    ${BLACKWELL_CONTROL} status
}
