#!/bin/sh

# Copyright (C) 2015, Blackwell Inc.
# OSSEC         Controls Blackwell
# Author:       Daniel B. Cid <dcid@ossec.net>
# Modified for Debian by Michael Starks (patch by Costas Drogos)

### BEGIN INIT INFO
# Provides:          ossec
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $network
# Should-Stop:       $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop Blackwell
# Description:       Controls Blackwell daemons
#
### END INIT INFO

BLACKWELL_HOME=BLACKWELL_HOME_TMP
BLACKWELL_CONTROL="$BLACKWELL_HOME/bin/blackwell-control"

start() {
    ${BLACKWELL_CONTROL} start
}

stop() {
    ${BLACKWELL_CONTROL} stop
}

status() {
    ${BLACKWELL_CONTROL} status
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
status)
    status
    ;;
*)
    echo "*** Usage: $0 {start|stop|restart|status}"
    exit 1
esac
