#!/bin/ksh
#
# name: ossec
# purpose: Init script for ossec-hids
# Copyright (C) 2015, Blackwell Inc.
# Aug. 07 2008 Chris Cuevas
#

BLACKWELL_HOME=BLACKWELL_HOME_TMP
BLACKWELL_CONTROL="$BLACKWELL_HOME/bin/blackwell-control"

case "$1" in
start)
    if [ -f "$BLACKWELL_CONTROL" ]; then
        echo "Starting Blackwell"
        ${BLACKWELL_CONTROL} start
    fi
    ;;
stop)
    if [ -f "$BLACKWELL_CONTROL" ]; then
        echo "Stopping Blackwell"
        ${BLACKWELL_CONTROL} stop
    fi
    ;;
status)
    if [ -f "$BLACKWELL_CONTROL" ]; then
        ${BLACKWELL_CONTROL} status
    fi
    ;;
restart)
    if [ -f "$BLACKWELL_CONTROL" ]; then
        ${BLACKWELL_CONTROL} restart
    fi
    ;;
*)
    echo "Usage: $0 (start | stop |restart | status)"
    exit 1
esac
