run-name: Build and Test Components

on:
  workflow_dispatch:

env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:
  Build-component-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build agent

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release software-properties-common libsystemd-dev
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo apt-get update
          sudo apt-get install -y clang-tidy-18 autopoint libtool zlib1g-dev \
            libgcrypt20-dev libmagic-dev libpopt-dev libmagic-dev libsqlite3-dev \
            liblua5.4-dev gettext libarchive-dev
        shell: bash

      - name: Set up Binary caching
        uses: ./.github/actions/vcpkg_related/cover_vcpkg_dependencies
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build component
        run: |
          mkdir src/build
          cd src/build
          cmake .. -DBUILD_TESTS=ON
          make -j $(nproc)

      - name: Run the tests
        run: |
          cd src/build && ./wazuh-agent &> status.log & sleep 3; pkill wazuh-agent
          cat src/build/status.log
