name: Execd integration tests tier 0 and 1 on Windows

on:
  workflow_dispatch:
  pull_request:
    paths:
        - ".github/workflows/integration-tests-execd-tier-0-1-win.yml"
        - "src/execd/**"
        - "src/Makefile"
        - "tests/integration/conftest.py"
        - "tests/integration/test_execd/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install mingw
        run: sudo apt install gcc-mingw-w64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 nsis -y
      - name: make deps
        run: make -C src deps TARGET=winagent -j2
      - name: make
        run: make -C src TARGET=winagent -j2
      - name: compress
        run: cd .. && zip -r wazuh.zip wazuh
        # Make folder and upload as artifacts.
      - name: Save compiled agent files
        run: |
          mkdir -p src/wazuh_compilation
          cp ../wazuh.zip src/wazuh_compilation/wazuh.zip
      # Upload build artifacts for the shared libraries.
      - name: Upload Artifact wazuh_compilation
        uses: actions/upload-artifact@v3
        with:
          name: wazuh_compilation
          path: src/wazuh_compilation

  run-test:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".github/workflows/.python-version-it"
          architecture: x64
      - name: Download Artifact wazuh_compilation
        uses: actions/download-artifact@v3
        with:
          name: wazuh_compilation
          path: C:\wazuh_compilation\
      - name: Decompress wazuh
        run: |
          Expand-Archive -LiteralPath C:\wazuh_compilation\wazuh.zip -DestinationPath C:\
      - name: Build wazuh installer
        run: |
          cd  C:\wazuh\src\win32
          .\wazuh-installer-build-msi.bat
      - name: Install wazuh
        run: |
          cd  C:\wazuh\src\win32
          .\wazuh-agent--.msi /q WAZUH_MANAGER="127.0.0.1"
      # Download and install integration tests framework.
      - name: Download and install integration tests framework
        run: |
          $BRANCH_NAME = "main"
          if ((git ls-remote --heads https://github.com/wazuh/qa-integration-framework.git $env:GITHUB_HEAD_REF) -ne "X") {
              $BRANCH_NAME = $env:GITHUB_HEAD_REF
          }
          git clone -b $BRANCH_NAME --single-branch https://github.com/wazuh/qa-integration-framework.git
          pip install qa-integration-framework/
          rm qa-integration-framework/ -r -force
      # Run execd integration tests.
      - name: Run execd integration tests
        run: |
          cd C:\wazuh\tests\integration
          python -m pytest -m win32 --tier 0 --tier 1 test_execd\
